apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: myrepo/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
              value: "file:/workspace/config-repo"
            - name: CONFIG_SERVER_USER
              valueFrom:
                secretKeyRef:
                  name: config-server-secret
                  key: username
            - name: CONFIG_SERVER_PASS
              valueFrom:
                secretKeyRef:
                  name: config-server-secret
                  key: password
